---
title: "Example News Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)

data <- read.csv("data/article_data.csv")

data <- data %>% 
  mutate(date = as.Date(date))

```

By Outlet
======================================================================

Inputs {.sidebar}
----------------------------------------------------------------------

Choose a news outlet and time frame

```{r}

selectInput("outlet", 
            label = "Select a news outlet:", 
            choices = sort(unique(data$publisher)), 
            selected = "AP")

dateRangeInput("dateRange", 
               "Date range:", 
               start = "2020-03-01", 
               end   = "2020-04-14") 

```

Column {data-width=750}
----------------------------------------------------------------------

### Plot: Candidate Mentions by Outlet

```{r}

renderPlot({
  
    # filter data based on input
  pltData <- data %>% 
    filter(date >= input$dateRange[1] & 
             date <= input$dateRange[2] & 
             publisher == input$outlet) %>% 
    select(-date, -publisher) %>% 
    summarize_all(funs(sum)) %>% 
    gather(candidate, count, Trump:Gabbard)
  
  pubPlot <- ggplot(pltData, aes(x = candidate,
                      y = count, 
                      fill = candidate)) +
    geom_bar(stat = "identity") 
  
  pubPlot
  
})


```

Column {data-width=250}
----------------------------------------------------------------------

### Table: Candidate Mentions by Outlet

```{r}

renderTable({
  
  tblData <- data %>% 
    filter(date >= input$dateRange[1] & 
             date <= input$dateRange[2] & 
             publisher == input$outlet) %>% 
    select(-date, -publisher) %>% 
    summarize_all(funs(sum)) %>% 
    gather(candidate, count, Trump:Gabbard)
  
  tblData
  
})

```

Over Time 
====================================================================

Inputs {.sidebar}
--------------------------------------------------------------------

```{r}

dateRangeInput("dateRange2", 
               "Date range:", 
               start = "2020-03-01", 
               end   = "2020-04-14") 

checkboxGroupInput("candidates",
                   label = "Select one or more candidates",
                   choices = c("Trump", "Sanders", "Biden", "Warren",
                               "Buttigieg", "Bloomberg", "Klobuchar", 
                               "Yang", "Steyer", "Gabbard"),
                   selected = c("Biden", "Sanders"))

```

Column
-----------------------------------------------------------------

### Plot: Candidate Mentions over Time

```{r}

renderPlot({
  
  candsToPlot <- input$candidates
  
  pltData <- data %>% 
    select(-publisher) %>% 
    gather(candidate, count, Trump:Gabbard) %>% 
    group_by(candidate, date) %>% 
    summarize(total_date = sum(count)) %>% 
    filter(date >= input$dateRange2[1] & 
             date <= input$dateRange2[2] &
             candidate %in% candsToPlot)
  
  timePlot <- ggplot(pltData, 
                     aes(x = date,
                         y = total_date,
                         group = candidate,
                         color = candidate)) +
    geom_line()
  
  timePlot
  
})

```





